### ISSUE TITLE
HTTP 429 too many requests

### ISSUE THREAD

**Issue by Kaden97** [Just-Some-Bots/MusicBot#2044] opened 2020-04-02 20:03 UTC
Please tick all applicable boxes.

- [ x] I am using Python 3.5.3 or higher (run `python --version` on the command line)
- [x ] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [ x] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [x ] The latest `master` version (release-260419)
- [ ] The latest `review` version

What type of issue are you creating?

- [ ] Bug
- [ ] Feature request
- [ ] Question

----

### Description of issue
Not sure why its happening I'm not great with code. I've had the bot and had it running and keep it up to date, for years now, but the other day it has started giving me the too many request error. 

EDIT: Anyone that comes a crossed this with this issues when hosting from your pc look to see if you have a rest button on your router. I had a "clog" in my router and that fixed it.

### Steps to reproduce

1. 

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**

**Comment by AleanaA** [comment] 2020-04-03 03:08
Duplicate of #1947

**Closed as completed by AleanaA** 2020-04-03 03:08 UTC
Labels: s/dupe
