### ISSUE TITLE
HTTP ERROR

### ISSUE THREAD

**Issue by NotVyx** [Just-Some-Bots/MusicBot#1983] opened 2019-11-08 16:17 UTC
Please tick all applicable boxes.

- [ x ] I am using Python 3.5.3 or higher (run `python --version` on the command line)
- [ x ] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [ x ] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [ x ] The latest `master` version (release-260419)
- [ ] The latest `review` version

What type of issue are you creating?

- [ x ] Bug
- [ ] Feature request
- [ ] Question

----

### Description of issue

I am unable to use the !play command, if I do I always get this error:

```
Joined Chill out Lounge/🎮 Game Chat - 1
135799822224588800/Jordan308#4178: !play basshunter
ERROR: Unable to download webpage: HTTP Error 429: Too Many Requests (caused by <HTTPError 429: 'Too Many Requests'>)
```

### Steps to reproduce

1. this is a fresh - out of the box install.

----

### Log file
https://pastebin.com/sQf5suUp

**Comment by AleanaA** [comment] 2019-11-08 16:19
Duplicate of #1960

**Closed as completed by AleanaA** 2019-11-08 16:19 UTC
