### ISSUE TITLE
CalledProcessError and Error starting bot

### ISSUE THREAD

**Issue by Dummyjaii10852** [Just-Some-Bots/MusicBot#1942] opened 2019-08-31 11:49 UTC
Please tick all applicable boxes.

- [x] I am using Python 3.5.3 or higher (run `python --version` on the command line)
- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [ ] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [x] The latest `master` version (release-260419)
- [ ] The latest `review` version

What type of issue are you creating?

- [x] Bug
- [ ] Feature request
- [x] Question

----

### Description of issue
This happen when i run the bot
[INFO] launcher: Starting sanity checks
[INFO] launcher: Checking for Python 3.5+
[INFO] launcher: Checking console encoding
[INFO] launcher: Setting console encoding to UTF-8
[INFO] launcher: Ensuring we're in the right environment
[INFO] launcher: Adding local bins/ folder to path
[INFO] launcher: Required checks passed.
[INFO] launcher: Optional checks passed.
[ERROR] launcher: Error starting bot
Traceback (most recent call last):
File "run.py", line 367, in main
from musicbot import MusicBot
File "C:\Users\Dummy\Desktop\Bot\MusicBot\musicbot_init_.py", line 7, in 
from .utils import _get_variable
File "C:\Users\Dummy\Desktop\Bot\MusicBot\musicbot\utils.py", line 3, in 
import aiohttp
ModuleNotFoundError: No module named 'aiohttp'
[INFO] launcher: Attempting to install dependencies...
Collecting pynacl==1.2.1 (from -r requirements.txt (line 1))
Downloading https://files.pythonhosted.org/packages/28/44/577007ec0e7c05ebf667
9a1d8f98e53576b337c3e87af2619d9e249ff20b/PyNaCl-1.2.1-cp37-cp37m-win32.whl (158k
B)

[CRITICAL] launcher: You may need to run as admin to install dependencies.

[INFO] launcher: All done.

C:\Users\Dummy\Desktop\Bot\MusicBot>

And this happen when i update it

[INFO] launcher: Starting sanity checks
[INFO] launcher: Checking for Python 3.5+
[INFO] launcher: Checking console encoding
[INFO] launcher: Setting console encoding to UTF-8
[INFO] launcher: Ensuring we're in the right environment
[INFO] launcher: Adding local bins/ folder to path
[INFO] launcher: Required checks passed.
[INFO] launcher: Optional checks passed.
[ERROR] launcher: Error starting bot
Traceback (most recent call last):
File "run.py", line 367, in main
from musicbot import MusicBot
File "C:\Users\Dummy\Desktop\Bot\MusicBot\musicbot_init_.py", line 7, in 
from .utils import _get_variable
File "C:\Users\Dummy\Desktop\Bot\MusicBot\musicbot\utils.py", line 3, in 
import aiohttp
ModuleNotFoundError: No module named 'aiohttp'
[INFO] launcher: Attempting to install dependencies...
Collecting pynacl==1.2.1 (from -r requirements.txt (line 1))
Downloading https://files.pythonhosted.org/packages/28/44/577007ec0e7c05ebf667
9a1d8f98e53576b337c3e87af2619d9e249ff20b/PyNaCl-1.2.1-cp37-cp37m-win32.whl (158k
B)

[CRITICAL] launcher: You may need to run as admin to install dependencies.

[INFO] launcher: All done.

C:\Users\Dummy\Desktop\Bot\MusicBot>

------------------------------

And this happen when i update it

Starting...
Passed Git checks...
You have modified files that are tracked by Git (e.g the bot's source files).
Should we try resetting the repo? You will lose local modifications. (y/n): y
HEAD is now at 3976fe0 Set bot version string to git describe result
Checking if we need to update the bot...
Already up to date.
Attempting to update dependencies...
Collecting pynacl==1.2.1 (from -r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/28/44/577007ec0e7c05ebf667
9a1d8f98e53576b337c3e87af2619d9e249ff20b/PyNaCl-1.2.1-cp37-cp37m-win32.whl (158k
B)
Traceback (most recent call last):
  File "update.py", line 17, in update_deps
    subprocess.check_call('"{}" -m pip install --no-warn-script-location --user
-U -r requirements.txt'.format(sys.executable), shell=True)
  File "C:\Users\Dummy\AppData\Local\Programs\Python\Python37-32\lib\subprocess.
py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '"C:\Users\Dummy\AppData\Local\Programs\P
ython\Python37-32\python.exe" -m pip install --no-warn-script-location --user -U
 -r requirements.txt' returned non-zero exit status 120.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "update.py", line 76, in <module>
    main()
  File "update.py", line 72, in main
    update_deps()
  File "update.py", line 19, in update_deps
    raise OSError("Could not update dependencies. You will need to run '\"{0}\"
-m pip install -U -r requirements.txt' yourself.".format(sys.executable))
OSError: Could not update dependencies. You will need to run '"C:\Users\Dummy\Ap
pData\Local\Programs\Python\Python37-32\python.exe" -m pip install -U -r require
ments.txt' yourself.

C:\Users\Dummy\Desktop\Bot\MusicBot>

### Steps to reproduce

1. 

----

### Log file
[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/3562410/musicbot.log)

Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**

**Comment by TheerapakG** [comment] 2019-08-31 12:14
> Could not update dependencies. You will need to run '"C:\Users\Dummy\Ap
pData\Local\Programs\Python\Python37-32\python.exe" -m pip install -U -r require
ments.txt' yourself.

Did you try this?

**Comment by Dummyjaii10852** [comment] 2019-08-31 12:21
Do you mean typing `-m pip install -U -r require
ments.txt' in the pytho.exe?

**Comment by TheerapakG** [comment] 2019-08-31 12:28
No, open cmd in the bot folder by typing cmd into the path bar when you're opening the bot folder. Paste the command
`python -m pip install -U -r requirements.txt` into it by **right-clicking**

**Comment by Dummyjaii10852** [comment] 2019-08-31 12:37
Ok now thx so much!But i have one more question,how can i switch my b ot when opening more than one?
Any command is used to control multiple bots?

**Comment by TheerapakG** [comment] 2019-08-31 12:44
No, and idk why you want to open more than one bot (assuming it's both MusicBot) since the bot can handle playing music in different servers at once.

**Comment by TheerapakG** [comment] 2019-08-31 13:09
Closing the issue because the issue is resolved.

**Closed as completed by TheerapakG** 2019-08-31 13:09 UTC
Labels: t/q&a, s/resolved
