### ISSUE TITLE
Error starting bot

### ISSUE THREAD

**Issue by Eevori** [Just-Some-Bots/MusicBot#2011] opened 2020-02-16 18:07 UTC
Please tick all applicable boxes.

- [x] I am using Python 3.5.3 or higher (run `python --version` on the command line)
- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [x] The latest `master` version (release-260419)
- [x] The latest `review` version

What type of issue are you creating?

- [x] Bug
- [ ] Feature request
- [x] Question

----

### Description of issue

im getting the error that the music bot cannot start "Error starting bot"

### Steps to reproduce

1. 

----

[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/4210517/musicbot.log)

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**

**Comment by TheerapakG** [comment] 2020-02-17 02:07
Duplicate of #1997

**Closed as completed by TheerapakG** 2020-02-17 02:07 UTC
Labels: s/dupe
