### ISSUE TITLE
Bot Joins visibly but doesnt finish joining in cmd

### ISSUE THREAD

**Issue by ken3b** [Just-Some-Bots/MusicBot#1963] opened 2019-10-16 02:40 UTC
Please tick all applicable boxes.

- [ e] I am using Python 3.5.3 or higher (run `python --version` on the command line)
- [ e] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [ e] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [ e] The latest `master` version (release-260419)
- [ ] The latest `review` version

What type of issue are you creating?

- [ e] Bug
- [ ] Feature request
- [ ] Question

----

### Description of issue
says attempting to join *channel*
but it never does

### Steps to reproduce

1. idk

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**

[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/3732232/musicbot.log)

**Comment by AleanaA** [comment] 2019-10-16 02:43
Duplicate of #1962

**Closed as completed by AleanaA** 2019-10-16 02:43 UTC
Labels: s/dupe
