### ISSUE TITLE
Suggestion : Command to remove a specific song from the queue.

### ISSUE THREAD

**Issue by beisong** [Just-Some-Bots/MusicBot#532] opened 2016-08-26 09:17 UTC
example: when you !queue it will show 
1. song1
2. song2
3. song3

"!remove 2" will remove song 2 from the queue

**Comment by arunesh90** [comment] 2016-08-26 15:55
Duplicate of #91 

This issue can be closed.

**Closed as completed** 2016-08-26 16:08 UTC
Labels: s/dupe
