### ISSUE TITLE
bot not playing any songs, constant youtube errors

### ISSUE THREAD

**Issue by sekeleader** [Just-Some-Bots/MusicBot#2002] opened 2019-12-18 01:02 UTC
Please tick all applicable boxes.

- [* ] I am using Python 3.5.3 or higher (run `python --version` on the command line)
- [ *] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [ *] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [ *] The latest `master` version (release-260419)
- [ ] The latest `review` version

What type of issue are you creating?

- [ *] Bug
- [ ] Feature request
- [ ] Question

----

### Description of issue
starting about 12/09/2019 the bot stopped playing ANY songs from youtube. i completely uninstalled the bot, python and git. then i reinstalled all the latest versions and only added the bot token in the options to create a control. even with default settings it would say the same thing. the attached is the log file.
[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/3976147/musicbot.log)

### Steps to reproduce

1. all i have to do is restart the bot and it happens again and again.

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**

**Comment by TheerapakG** [comment] 2019-12-18 01:16
Duplicate of #1947

**Closed as completed by TheerapakG** 2019-12-18 01:16 UTC
Labels: s/dupe
