### ISSUE TITLE
[Feature request] Support chiptune modules files.

### ISSUE THREAD

**Issue by luckcolors** [Just-Some-Bots/MusicBot#89] opened 2016-02-13 15:05 UTC
Hello i just tried you bot and it's amazing it works great.
But i would also like it to play chiptune files .xm .mod .it .etc. for more info on chiptunes check https://woolyss.com/chipmusic.php.
For supporting the playtrouught of the chiptunes you could use http://lib.openmpt.org/libopenmpt/
from the open mtp tracker. It supports all chitunes formats except some like .sid (c64 commodore) and .ftm(famitracker) which are less common (for complete supported files see http://openmpt.org/features).
I hope you can really implement this feature. Thanks in advance :P.

**Comment by imayhaveborkedit** [comment] 2016-02-13 18:42
If ffmpeg supports it, the bot supports it.  I have nothing to do with it.

**Comment by imayhaveborkedit** [comment] 2016-02-13 18:47
It has come to my attention that while the bot doesn't seem to be able to play these, ffmpeg should technically support these.  I'll have to figure out why ffmpeg isn't converting them.

Random link with various MODs: http://paul.chattaway.com/clacomp/mods/modlist.html

**Comment by imayhaveborkedit** [comment] 2016-02-13 18:58
Ok I figured it out.  Turns out ffmpeg just doesn't like the `.mp3` extension on the file when youtube_dl downloads it (we just slap `.mp3` on everything and usually ffmpeg is fine with it). I'll add this to my todo list.  This will actually probably be fixed when I fix how files are managed though.

**Comment by luckcolors** [comment] 2016-02-17 12:53
You can probably ease the download by using wget when a direct link to a file is given.
Eg. http://example.org/chiptune.xm

**Comment by imayhaveborkedit** [comment] 2016-02-17 13:38
It's not a download issue, youtube-dl takes care of that.  The issue is that everything gets renamed with an `.mp3` extension, regardless of content.  Since ffmpeg doesn't like that, it has to be changed for them to work.

**Comment by imayhaveborkedit** [comment] 2016-05-02 21:56
This should be fixed now as the bot saved files with their actual extension.

**Closed as completed by imayhaveborkedit** 2016-05-02 21:56 UTC
Labels: t/bug
