### ISSUE TITLE
Play command not working

### ISSUE THREAD

**Issue by ohjavanna** [Just-Some-Bots/MusicBot#2235] opened 2021-09-12 04:08 UTC
Please tick all applicable boxes.

- [x] I am using Python 3.5.3 or higher (run `python --version` on the command line)
- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [ ] The latest `master` version (release-260419)
- [x] The latest `review` version

What type of issue are you creating?

- [x] Bug
- [ ] Feature request
- [ ] Question

----

### Description of issue

The bot is not adding music. The play command does not work. The bot appears to be typing for a while and then does nothing.

### Steps to reproduce

1. Use the play command.

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**
[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/7148982/musicbot.log)

**Comment by AutumnClove** [comment] 2021-09-12 05:56
It shows that it's downloading just fine in your logs. I am unable to reproduce this issue on my end, have you done a git pull recently and made sure you're up to date with everything?

**Comment by AutumnClove** [comment] 2021-09-16 11:31
Since I'm unable to reproduce this I'm going to go ahead and close it. You can always ask for help in the [discord server](https://www.discord.gg/bots)

**Closed as completed by AutumnClove** 2021-09-16 11:31 UTC
