### ISSUE TITLE
[ERROR:bot] Exception in on_message

### ISSUE THREAD

**Issue by lukasblacha** [Just-Some-Bots/MusicBot#2322] opened 2023-01-24 10:09 UTC
### What went wrong?

[ERROR:bot] Exception in on_message
Traceback (most recent call last):
  File "/home/administrator/MusicBot/musicbot/bot.py", line 4064, in on_message
    content = self._gen_embed()
  File "/home/administrator/MusicBot/musicbot/bot.py", line 1361, in _gen_embed
    icon_url=self.user.avatar_url,
AttributeError: 'ClientUser' object has no attribute 'avatar_url'

### How do we reproduce this?

Use a Command that will generate an embed.

Quick FIX:
Go to musicbot/bot.py > then line no. 1361 > replace "icon_url=self.user.avatar_url" with "icon_url=self.user.avatar.url" > SAVE

This will fix the Bug

### Which version of the bot are you using?

release-151221

### Which operating system are you using?

Ubuntu 18.04 or higher

### Just checking...

- [X] I have confirmed that my issue has not already been reported.
- [X] I am using Python 3.8 or higher.
- [X] I have updated my Python dependencies.

**Comment by AleanaA** [comment] 2023-01-24 11:34
Duplicate of #2312

**Closed as completed by AleanaA** 2023-01-24 11:34 UTC
Labels: t/bug, needs triage
