### ISSUE TITLE
Can't run

### ISSUE THREAD

**Issue by bananakiller192** [Just-Some-Bots/MusicBot#1999] opened 2019-12-07 22:22 UTC
Please tick all applicable boxes.

- [x ] I am using Python 3.5.3 or higher (run `python --version` on the command line)
- [x ] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [ x] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [x ] The latest `master` version (release-260419)
- [x ] The latest `review` version

What type of issue are you creating?

- [x ] Bug
- [ ] Feature request
- [ ] Question

----

### Description of issue
When i run the run.bat i get this issue 

[INFO] launcher: Starting sanity checks
[INFO] launcher: Checking for Python 3.5+
[INFO] launcher: Checking console encoding
[INFO] launcher: Setting console encoding to UTF-8
[INFO] launcher: Ensuring we're in the right environment
[INFO] launcher: Adding local bins/ folder to path
[INFO] launcher: Required checks passed.
[INFO] launcher: Optional checks passed.
[INFO] launcher: Moving old musicbot log
Traceback (most recent call last):
  File "run.py", line 438, in <module>
    main()
  File "run.py", line 347, in main
    finalize_logging()
  File "run.py", line 179, in finalize_logging
    dlh.setFormatter(logging.Formatter('.'))
  File "C:\Users\Banan\AppData\Local\Programs\Python\Python38\lib\logging\__init__.py", line 576, in __init__
    self._style.validate()
  File "C:\Users\Banan\AppData\Local\Programs\Python\Python38\lib\logging\__init__.py", line 429, in validate
    raise ValueError("Invalid format '%s' for '%s' style" % (self._fmt, self.default_format[0]))
ValueError: Invalid format '.' for '%' style
----

### Log file
[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/3935624/musicbot.log)

**Comment by TheerapakG** [comment] 2019-12-07 22:41
Duplicate of #1985, use review branch or downgrade your Python to 3.5.4-3.7

**Closed as completed by TheerapakG** 2019-12-07 22:41 UTC
Labels: s/dupe
