### ISSUE TITLE
Loop and Loop all

### ISSUE THREAD

**Issue by AlexMayne5** [Just-Some-Bots/MusicBot#1837] opened 2019-02-04 19:11 UTC
Please tick all applicable boxes.

- [ /] I am using Python 3.5 or higher (run `python --version` on the command line)
- [ /] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [ /] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [ /] The latest `master` version (1.9.8)

What type of issue are you creating?
- [ /] Feature request

----

### Description of Feature
Can we have a loop and a loop 1
![capture101](https://user-images.githubusercontent.com/46424598/52230967-9b843a00-28b0-11e9-8d90-dd81cd26d693.PNG)

**Comment by MattBSG** [comment] 2019-02-05 03:12
Duplicate of #1590

**Closed as completed by MattBSG** 2019-02-05 03:12 UTC
Labels: s/dupe, t/request
