### ISSUE TITLE
How to install or uninstall? Or what i need to do?

### ISSUE THREAD

**Issue by x1tko0** [Just-Some-Bots/MusicBot#1741] opened 2018-09-21 09:32 UTC
Hi, guys. I have a problem. I just missclicked and deleted folder with MusicBot, now i tryin to install and have this problem https://service.crazypanda.ru/v/monosnap/2018-09-21-12-26-00-4z6pm.png . Im tryin to clone, but have this https://service.crazypanda.ru/v/monosnap/2018-09-21-12-30-39-r4fqe.png . Help me pls, what i need to do?

**Comment by TheerapakG** [comment] 2018-09-21 09:49
try open git bash in the directory you want to install and run `git clone https://github.com/Just-Some-Bots/MusicBot.git MusicBot -b master`

**Comment by x1tko0** [comment] 2018-09-21 09:56
> try open git bash in the directory you want to install and run `git clone https://github.com/Just-Some-Bots/MusicBot.git MusicBot -b master`

https://service.crazypanda.ru/v/monosnap/2018-09-21-12-56-16-pftqf.png - This error

**Comment by TheerapakG** [comment] 2018-09-21 10:07
By 'git bash' I mean that you need to use [Git for Windows](http://gitforwindows.org/) not Github Desktop (usually Github Desktop work but in some case TLS handshake gone wrong or something similar, idk)
During the setup, tick `Use Git from the Windows Command Prompt`, `Checkout Windows-style, commit Unix-style endings` and `Use MinTTY (the default terminal MSYS2)`.
Open Git Bash by right-clicking an empty space inside of a folder in the directory you want to install and click `Git Bash here`.

**Comment by x1tko0** [comment] 2018-09-21 10:40
> By 'git bash' I mean that you need to use [Git for Windows](http://gitforwindows.org/) not Github Desktop (usually Github Desktop work but in some case TLS handshake gone wrong or something similar, idk)
> During the setup, tick `Use Git from the Windows Command Prompt`, `Checkout Windows-style, commit Unix-style endings` and `Use MinTTY (the default terminal MSYS2)`.
> Open Git Bash by right-clicking an empty space inside of a folder in the directory you want to install and click `Git Bash here`.

https://service.crazypanda.ru/v/monosnap/2018-09-21-13-24-05-p7o8z.png - This error

**Comment by TheerapakG** [comment] 2018-09-21 10:53
Are you using this on a corporate network or have antivirus installed? If you have antivirus try to disable it when cloning. They might block git's attempts to check certificate. If you're on a corporate network then I can't help you much. You can try reinstall git and tick `Use the native Windows Secure Channel library` since some firewall does SSL inspection which generates its own certificate to a man in the middle of the connection. The certs then added to Windows trust store.

**Comment by x1tko0** [comment] 2018-09-21 11:11
> Are you using this on a corporate network or have antivirus installed? If you have antivirus try to disable it when cloning. They might block git's attempts to check certificate. If you're on a corporate network then I can't help you much. You can try reinstall git and tick `Use the native Windows Secure Channel library` since some firewall does SSL inspection which generates its own certificate to a man in the middle of the connection. The certs then added to Windows trust store.

I turned off antivirus and it works! But, i have another thing, while runin "run.bat" - https://service.crazypanda.ru/v/monosnap/2018-09-21-14-11-19-2mj1e.png

**Comment by TheerapakG** [comment] 2018-09-21 11:12
did you run update.bat?

**Comment by x1tko0** [comment] 2018-09-21 12:35
I did, but https://service.crazypanda.ru/v/monosnap/2018-09-21-15-35-02-h67sj.png

**Comment by TheerapakG** [comment] 2018-09-21 12:38
> I did, but https://service.crazypanda.ru/v/monosnap/2018-09-21-15-35-02-h67sj.png

now I see what doesn't work here ... uninstall python 3.5.2 and install python 3.7 because currently musicbot require dependencies that don't work on Python 3.5.2 or below

**Comment by x1tko0** [comment] 2018-09-21 12:57
> > I did, but https://service.crazypanda.ru/v/monosnap/2018-09-21-15-35-02-h67sj.png
> 
> now I see what doesn't work here ... uninstall python 3.5.2 and install python 3.7 because currently musicbot require dependencies that don't work on Python 3.5.2 or below

Installed 3.7 python. Doin run.bat https://service.crazypanda.ru/v/monosnap/2018-09-21-15-56-22-scpci.png , then update.bat, the same thing https://service.crazypanda.ru/v/monosnap/2018-09-21-15-57-20-rjcni.png

**Comment by TheerapakG** [comment] 2018-09-21 13:01
type `python -m pip install -U -r -requirements.txt` in cmd (elevated)  __without__ separating it

**Comment by x1tko0** [comment] 2018-09-21 13:18
> type `python -m pip install -U -r -requirements.txt' in cmd **without** separating it as you did

https://service.crazypanda.ru/v/monosnap/2018-09-21-16-17-12-ixf7x.png this thing, sry, im noob, and dont understand what i do wrong ;(

**Comment by TheerapakG** [comment] 2018-09-21 13:18
I typed it wrong sorry `python -m pip install -U -r requirements.txt`
I just typed it hurriedly from my memory without checking it. sorry. there's no hyphen in front of requirements.txt

**Comment by TheerapakG** [comment] 2018-09-21 13:47
Does it work?
If it works, you can close the issue by yourself.

**Comment by x1tko0** [comment] 2018-09-21 13:48
> Does it work?
> If it works, you can close the issue by yourself.

It works, Thanks! But, bot doesnt autosummons to voice channel, id correct ;\

**Comment by TheerapakG** [comment] 2018-09-21 13:50
it autosummon to the voice channel you're in when you start the bot. After that, use summon.

**Comment by x1tko0** [comment] 2018-09-21 13:51
Yeah, i know, but earlier it autosummoned himself directly to voice chat, after start up, is that not workin anymore?

**Comment by TheerapakG** [comment] 2018-09-21 13:52
it autosummoned on startup directly to voice chat.

**Comment by x1tko0** [comment] 2018-09-21 13:55
My bot doesnt, just stayin in lobby, i need to use /summon every time. Did it last 5 times, only works like that

**Comment by TheerapakG** [comment] 2018-09-21 13:56
Is the bot know that you're the owner (the msg on startup) and you're in a voice channel when bot start?

**Comment by x1tko0** [comment] 2018-09-21 13:58
Yeah, some error on log in https://service.crazypanda.ru/v/monosnap/2018-09-21-16-57-34-gy0k1.png

**Comment by TheerapakG** [comment] 2018-09-21 14:01
That is not what I expect ... upload full log pls. log can be found at logs/musicbot.log

**Comment by x1tko0** [comment] 2018-09-21 14:03
Log before that https://service.crazypanda.ru/v/monosnap/2018-09-21-17-02-46-qv14t.png

**Comment by TheerapakG** [comment] 2018-09-21 14:04
Full log can be found at logs/musicbot.log . Upload file by dragging them into the comment box.

**Comment by x1tko0** [comment] 2018-09-21 14:06
[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/2405641/musicbot.log)

**Comment by TheerapakG** [comment] 2018-09-21 14:10
Are you running another bot? Make sure you're running only an instance of the bot.

**Comment by x1tko0** [comment] 2018-09-21 14:11
Nope, only 1 bot, on 2 different servers, but 1 bot, run.bat.

**Comment by TheerapakG** [comment] 2018-09-21 14:14
Check if something is using a log file. Close them

If not, try restarting your computer
If something is using the file and causing this, then a restart will almost certainly solve some issue of logging

**Comment by TheerapakG** [comment] 2018-09-21 14:28
did you start the bot again? if so send me the log file please

**Comment by x1tko0** [comment] 2018-09-21 14:39
[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/2405790/musicbot.log)
Yeah, i did, same thing

**Comment by TheerapakG** [comment] 2018-09-21 14:49
Today is a permission error day huh? I'm not sure about this error either. Colorama is considerably the least problematic dependency.

**Comment by TheerapakG** [comment] 2018-09-21 14:51
This seems to be #1559 but I don't have the issue (I use python 3.7). Not sure why it appears here either. Python 3.7 shouldn't have this issue

**Comment by x1tko0** [comment] 2018-09-21 14:57
Anyway, thanks alot, ill just summon him every time, not too hard ;)

**Comment by TheerapakG** [comment] 2018-09-21 15:00
actually, this shouldn't affect the autojoining but I can't help you much beyond this either

**Comment by x1tko0** [comment] 2018-09-21 15:05
> actually, this shouldn't affect the autojoining but I can't help you much beyond this either

I understand, u aleady did great job, thanks a lot!

**Closed as completed** 2018-09-21 15:05 UTC

**Comment by AutumnClove** [comment] 2018-09-21 16:54
Have you modified your registry in any way? I think this issue might be related to windows and it's pesky permissions(going off the log it says winerror31) do you have python installed to path and all users? I noticed yesterday that even when you click install for all users if you don't click advanced and select it from there it doesn't always work right? Maybe try installing the optional libraries? 

As for auto joining, I would suggest binding the bot to a voice channel to join on start up, however having to use !summon if it's not in a voice channel is intended behavior.

**Comment by x1tko0** [comment] 2018-09-26 07:27
> Have you modified your registry in any way? I think this issue might be related to windows and it's pesky permissions(going off the log it says winerror31) do you have python installed to path and all users? I noticed yesterday that even when you click install for all users if you don't click advanced and select it from there it doesn't always work right? Maybe try installing the optional libraries?
> 
> As for auto joining, I would suggest binding the bot to a voice channel to join on start up, however having to use !summon if it's not in a voice channel is intended behavior.

Didnt modified my registry. Ty for the help, maybe ill try to reinstall libraries.
