### ISSUE TITLE
SSL Error.

### ISSUE THREAD

**Issue by thestrangehosterr** [Just-Some-Bots/MusicBot#2114] opened 2020-08-07 09:42 UTC
Please tick all applicable boxes.

- [✓] I am using Python 3.5.3 or higher (run `python --version` on the command line)
- [✓] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [✓] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [✓] The latest `master` version (release-260419)
- [ ] The latest `review` version

What type of issue are you creating?

- [✓] Bug
- [ ] Feature request
- [ ] Question

----

### Description of issue
This is what I get, I have AioHTTP updated fully.
`[ERROR] launcher: Error starting bot
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/aiohttp/connector.py", line 936, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore  # noqa
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/base_events.py", line 802, in create_connection
    sock, protocol_factory, ssl, server_hostname)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/base_events.py", line 828, in _create_connection_transport
    yield from waiter
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/sslproto.py", line 503, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/sslproto.py", line 201, in feed_ssldata
    self._sslobj.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 683, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)t`

### Steps to reproduce

1. run ./start.sh
[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/5040560/musicbot.log)

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**

**Comment by AleanaA** [comment] 2020-08-08 04:46
Duplicate of #2075

**Closed as completed by AleanaA** 2020-08-08 04:46 UTC
