### ISSUE TITLE
Youtube-DL : HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by Razorbackfr** [Just-Some-Bots/MusicBot#2064] opened 2020-04-28 12:38 UTC
Please tick all applicable boxes.

- [ x] I am using Python 3.5.3 or higher (run `python --version` on the command line)
- [ x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x ] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [ ] The latest `master` version (release-260419)
- [ x] The latest `review` version

What type of issue are you creating?

- [ x] Bug
- [ ] Feature request
- [ ] Question

----

### Description of issue

The robot cannot download and play music from the autoplay list, and when music is added by a user, the robot must be restarted for the music to play.

the! skip command also returns the error, so it is impossible for the bot to start the music that follows

### Steps to reproduce

1.
----

### Log file
6.9145855903625488] 2020-04-28 14:03:13,150 - WARNING - musicbot.player | In player.py::MainThread(3082481344), line 274 in _play: Failed to get entry, retrying
Traceback (most recent call last):
  File "/home/valentin/.local/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 1926, in process_info
    success = dl(filename, info_dict)
  File "/home/valentin/.local/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 1865, in dl
    return fd.download(name, info)
  File "/home/valentin/.local/lib/python3.7/site-packages/youtube_dl/downloader/common.py", line 366, in download
    return self.real_download(filename, info_dict)
  File "/home/valentin/.local/lib/python3.7/site-packages/youtube_dl/downloader/http.py", line 341, in real_download
    establish_connection()
  File "/home/valentin/.local/lib/python3.7/site-packages/youtube_dl/downloader/http.py", line 109, in establish_connection
    ctx.data = self.ydl.urlopen(request)
  File "/home/valentin/.local/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 2238, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/valentin/MusicBot/musicbot/entry.py", line 371, in _really_download
    result = await self.playlist.downloader.extract_info(self.playlist.loop, self.url, download=True)
  File "/home/valentin/MusicBot/musicbot/downloader.py", line 84, in extract_info
    return await loop.run_in_executor(self.thread_pool, functools.partial(self.unsafe_ytdl.extract_info, *args, **kwargs))
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/valentin/.local/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 808, in extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "/home/valentin/.local/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 863, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "/home/valentin/.local/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 1644, in process_video_result
    self.process_info(new_info)
  File "/home/valentin/.local/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 1928, in process_info
    self.report_error('unable to download video data: %s' % error_to_compat_str(err))
  File "/home/valentin/.local/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 625, in report_error
    self.trouble(error_message, tb)
  File "/home/valentin/.local/lib/python3.7/site-packages/youtube_dl/YoutubeDL.py", line 595, in trouble
    raise DownloadError(message, exc_info)
youtube_dl.utils.DownloadError: [0;31mERROR:[0m unable to download video data: HTTP Error 403: Forbidden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/valentin/MusicBot/musicbot/player.py", line 272, in _play
    entry = await self.playlist.get_next_entry()
  File "/home/valentin/MusicBot/musicbot/playlist.py", line 334, in get_next_entry
    return await entry.get_ready_future()
  File "/home/valentin/MusicBot/musicbot/entry.py", line 228, in _download
    await self._really_download()
  File "/home/valentin/MusicBot/musicbot/entry.py", line 374, in _really_download
    raise ExtractionError(e)
musicbot.exceptions.ExtractionError: [0;31mERROR:[0m unable to download video data: HTTP Error 403: Forbidden
[7.0206325054168701] 2020-04-28 14:03:13,256 - DEBUG - musicbot.bot | In bot.py::MainThread(3082481344), line 546 in on_player_stop: Running on_player_stop

**Comment by TheerapakG** [comment] 2020-04-28 13:02
Duplicate of #2060

**Closed as completed by TheerapakG** 2020-04-28 13:02 UTC
Labels: s/invalid, t/lib
