### ISSUE TITLE
MusicBot not working after I updated to the newest version

### ISSUE THREAD

**Issue by bjarkeh14** [Just-Some-Bots/MusicBot#1869] opened 2019-04-10 07:45 UTC
Hi

I can't start the bot after I updated it to the newest version 1.9.8_4.

this is what I get in the log when i start it. The bot is running on a full updated ubuntu

### Log file
[192.901372910] 2019-04-10 09:39:43,363 - INFO - launcher: Starting sanity checks
[193.440198898] 2019-04-10 09:39:43,363 - INFO - launcher: Checking for Python 3.5+
[193.677663803] 2019-04-10 09:39:43,364 - INFO - launcher: Checking console encoding
[193.920135498] 2019-04-10 09:39:43,364 - INFO - launcher: Ensuring we're in the right environment
[1573.335886002] 2019-04-10 09:39:44,743 - INFO - launcher: Required checks passed.
[1574.568748474] 2019-04-10 09:39:44,745 - INFO - launcher: Optional checks passed.
[1582.668066025] 2019-04-10 09:39:44,753 - INFO - launcher: Moving old musicbot log

######################### PRE-RUN SANITY CHECKS PASSED #########################

[3.1373348236083984] 2019-04-10 09:39:46,307 - WARNING - musicbot.config | In config.py::MainThread(140217732200256), line 116 in run_checks: i18n file does not exist. Trying to fallback to config/i18n/en.json.
[3.1410639286041260] 2019-04-10 09:39:46,311 - INFO - musicbot.config | In config.py::MainThread(140217732200256), line 127 in run_checks: Using i18n: config/i18n/en.json
[3.1435990333557129] 2019-04-10 09:39:46,314 - DEBUG - musicbot.bot | In bot.py::MainThread(140217732200256), line 226 in _setup_logging: Set logging level to INFO
[3.1594309806823730] 2019-04-10 09:39:46,329 - DEBUG - musicbot.json | In json.py::MainThread(140217732200256), line 8 in __init__: Init JSON obj with config/i18n/en.json
[3.2276580333709717] 2019-04-10 09:39:46,398 - INFO - musicbot.bot | In bot.py::MainThread(140217732200256), line 91 in __init__: Starting MusicBot 1.9.8_4
[3.2280883789062500] 2019-04-10 09:39:46,398 - INFO - musicbot.bot | In bot.py::MainThread(140217732200256), line 97 in __init__: Loaded autoplaylist with 288 entries
[6.2264654636383057] 2019-04-10 09:39:49,396 - DEBUG - musicbot.bot | In bot.py::MainThread(140217732200256), line 922 in on_ready: Connection established, ready to go.
[6.2266497611999512] 2019-04-10 09:39:49,397 - DEBUG - musicbot.bot | In bot.py::MainThread(140217732200256), line 340 in _cache_app_info: Caching app info
[6.4393458366394043] 2019-04-10 09:39:49,609 - DEBUG - musicbot.bot | In bot.py::MainThread(140217732200256), line 744 in _scheck_ensure_env: Ensuring data folders exist
[6.4502787590026855] 2019-04-10 09:39:49,620 - DEBUG - musicbot.bot | In bot.py::MainThread(140217732200256), line 760 in _scheck_server_permissions: Checking server permissions
[6.4503982067108154] 2019-04-10 09:39:49,620 - DEBUG - musicbot.bot | In bot.py::MainThread(140217732200256), line 764 in _scheck_autoplaylist: Auditing autoplaylist
[6.4504730701446533] 2019-04-10 09:39:49,620 - DEBUG - musicbot.bot | In bot.py::MainThread(140217732200256), line 768 in _scheck_configs: Validating config
[6.4505450725555420] 2019-04-10 09:39:49,621 - DEBUG - musicbot.config | In config.py::MainThread(140217732200256), line 217 in async_validate: Validating options...
[6.4506163597106934] 2019-04-10 09:39:49,621 - DEBUG - musicbot.config | In config.py::MainThread(140217732200256), line 231 in async_validate: Acquired owner id via API
[6.4506795406341553] 2019-04-10 09:39:49,621 - DEBUG - musicbot.bot | In bot.py::MainThread(140217732200256), line 771 in _scheck_configs: Validating permissions config
[6.4507486820220947] 2019-04-10 09:39:49,621 - DEBUG - musicbot.permissions | In permissions.py::MainThread(140217732200256), line 94 in async_validate: Validating permissions...
[6.4508242607116699] 2019-04-10 09:39:49,621 - DEBUG - musicbot.permissions | In permissions.py::MainThread(140217732200256), line 98 in async_validate: Fixing automatic owner group
[6.4508922100067139] 2019-04-10 09:39:49,621 - INFO - musicbot.bot | In bot.py::MainThread(140217732200256), line 939 in on_ready: Connected: 299677827064922113/Dj NotNice#6465
[6.4513466358184814] 2019-04-10 09:39:49,621 - INFO - musicbot.bot | In bot.py::MainThread(140217732200256), line 947 in on_ready: Owner:     186238116091265027/Bjalken#7105

[6.4515933990478516] 2019-04-10 09:39:49,622 - INFO - musicbot.bot | In bot.py::MainThread(140217732200256), line 950 in on_ready: Guild List:
[6.4517669677734375] 2019-04-10 09:39:49,622 - INFO - musicbot.bot | In bot.py::MainThread(140217732200256), line 954 in on_ready:  - SaunaKlubben
[6.4519925117492676] 2019-04-10 09:39:49,622 - INFO - musicbot.bot | In bot.py::MainThread(140217732200256), line 1010 in on_ready: Not bound to any text channels
[6.4522321224212646] 2019-04-10 09:39:49,622 - INFO - musicbot.bot | In bot.py::MainThread(140217732200256), line 1023 in on_ready: Autojoining voice channels:
[6.4524078369140625] 2019-04-10 09:39:49,622 - INFO - musicbot.bot | In bot.py::MainThread(140217732200256), line 1024 in <listcomp>:  - SaunaKlubben/Music 🎶
[6.4527053833007812] 2019-04-10 09:39:49,623 - INFO - musicbot.bot | In bot.py::MainThread(140217732200256), line 279 in _join_startup_channels: Attempting to join SaunaKlubben/Music 🎶
[6.9775261878967285] 2019-04-10 09:39:50,147 - DEBUG - musicbot.bot | In bot.py::MainThread(140217732200256), line 307 in _join_startup_channels: Error joining SaunaKlubben/Music 🎶
Traceback (most recent call last):
  File "/home/administrator/MusicBot/musicbot/bot.py", line 292, in _join_startup_channels
    player = await self.get_player(channel, create=True, deserialize=self.config.persistent_queue)
  File "/home/administrator/MusicBot/musicbot/bot.py", line 419, in get_player
    voice_client = await self.get_voice_client(channel)
  File "/home/administrator/MusicBot/musicbot/bot.py", line 384, in get_voice_client
    return await channel.connect(timeout=60, reconnect=True)
  File "/usr/local/lib/python3.6/dist-packages/discord/abc.py", line 981, in connect
    await voice.connect(reconnect=reconnect)
  File "/usr/local/lib/python3.6/dist-packages/discord/voice_client.py", line 214, in connect
    await self.ws.poll_event()
  File "/usr/local/lib/python3.6/dist-packages/discord/gateway.py", line 731, in poll_event
    await self.received_message(json.loads(msg))
  File "/usr/local/lib/python3.6/dist-packages/discord/gateway.py", line 685, in received_message
    await self.load_secret_key(data)
  File "/usr/local/lib/python3.6/dist-packages/discord/gateway.py", line 725, in load_secret_key
    await self.speak()
  File "/usr/local/lib/python3.6/dist-packages/discord/gateway.py", line 664, in speak
    'speaking': int(state),
TypeError: int() argument must be a string, a bytes-like object or a number, not 'SpeakingState'
[7.0285823345184326] 2019-04-10 09:39:50,199 - ERROR - musicbot.bot | In bot.py::MainThread(140217732200256), line 308 in _join_startup_channels: Failed to join SaunaKlubben/Music 🎶
[7.0290684700012207] 2019-04-10 09:39:50,199 - ERROR - musicbot.bot | In bot.py::MainThread(140217732200256), line 910 in on_error: Exception in on_voice_state_update
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/discord/client.py", line 242, in _run_event
    await coro(*args, **kwargs)
  File "/home/administrator/MusicBot/musicbot/bot.py", line 2842, in on_voice_state_update
    player = await self.get_player(channel)
  File "/home/administrator/MusicBot/musicbot/bot.py", line 431, in get_player
    'Use %ssummon to summon it to your voice channel.' % self.config.command_prefix)
musicbot.exceptions.CommandError: The bot is not in a voice channel.  Use !summon to summon it to your voice channel.

**Comment by TheerapakG** [comment] 2019-04-10 07:56
duplicate of #1866

**Closed as completed** 2019-04-22 15:38 UTC
Labels: s/dupe
