### ISSUE TITLE
Traceback Error

### ISSUE THREAD

**Issue by train21** [Just-Some-Bots/MusicBot#931] opened 2017-02-12 02:47 UTC
[0;31mERROR:[0m Signature extraction failed: Traceback (most recent call last):
  File "/home/dylan/.local/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 1035, in _decrypt_signature
    video_id, player_url, s
  File "/home/dylan/.local/lib/python3.5/site-packages/youtube_dl/extractor/youtube.py", line 949, in _extract_signature_function
    errnote='Download of %s failed' % player_url)
  File "/home/dylan/.local/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 519, in _download_webpage
    res = self._download_webpage_handle(url_or_request, video_id, note, errnote, fatal, encoding=encoding, data=data, headers=headers, query=query)
  File "/home/dylan/.local/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 426, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query)
  File "/home/dylan/.local/lib/python3.5/site-packages/youtube_dl/extractor/common.py", line 406, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "/home/dylan/.local/lib/python3.5/site-packages/youtube_dl/YoutubeDL.py", line 2000, in urlopen
    req = sanitized_Request(req)
  File "/home/dylan/.local/lib/python3.5/site-packages/youtube_dl/utils.py", line 525, in sanitized_Request
    return compat_urllib_request.Request(sanitize_url(url), *args, **kwargs)
  File "/usr/lib/python3.5/urllib/request.py", line 269, in __init__
    self.full_url = url
  File "/usr/lib/python3.5/urllib/request.py", line 295, in full_url
    self._parse()
  File "/usr/lib/python3.5/urllib/request.py", line 324, in _parse
    raise ValueError("unknown url type: %r" % self.full_url)
ValueError: unknown url type: '/yts/jsbin/player-en_US-vfl8LqiZp/base.js'
 (caused by ValueError("unknown url type: '/yts/jsbin/player-en_US-vfl8LqiZp/base.js'",))

I dont know how to fix, I already installed the latest youtube_dl

**Comment by train21** [comment] 2017-02-12 03:13
Also on Ubuntu MATE 16.04 LTS

**Comment by arunesh90** [comment] 2017-02-12 03:22
Duplicate of #873

**Closed as completed by arunesh90** 2017-02-12 03:22 UTC
