### ISSUE TITLE
Feature Request: Option for !play to act as !summon additionally to !play

### ISSUE THREAD

**Issue by LegalSmeagol** [Just-Some-Bots/MusicBot#2079] opened 2020-05-30 23:23 UTC
Please tick all applicable boxes.

- [+] I am using Python 3.5.3 or higher (run `python --version` on the command line)
- [+] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [+] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [+] The latest `master` version (release-260419)
- [ ] The latest `review` version

What type of issue are you creating?

- [ ] Bug
- [+] Feature request
- [ ] Question

----

### Description of issue
First of all I'd like to say how much I'm in love with this bot. My feature request is to adopt a similar feature to other music bots, namely Groovy and Rhythm whereby !play summons the bot and proceeds to play, negating the need to type !summon and then !play. It would allow a much smoother experience.

Of course, with any options like this, it could be a good idea to make this an optional feature where people can choose whether to enable "easy summoning?" or not. You get the gist. Would love to see this edition to the bot which so far has my utmost admiration - simply a beautiful bot, well done.

### Steps to reproduce

1. N/A

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**

N/A

**Comment by AleanaA** [comment] 2020-05-30 23:29
See #2024 for this, there's a possibility it will be merged in the future, until then you're free to use the pr's branch to implement this feature.
Duplicate of #837

**Closed as completed by AleanaA** 2020-05-30 23:29 UTC
