### ISSUE TITLE
Repeat command don't work

### ISSUE THREAD

**Issue by Licons** [Just-Some-Bots/MusicBot#1375] opened 2017-10-20 03:20 UTC
I called command "repeat" to repeat my songs but nothing happened.

This is my picture.
https://imgur.com/a/tEZBh

Thanks.

**Comment by Zenrac** [comment] 2017-10-21 22:45
Come on, how we're supposed to help you ?

**Comment by FIERCEDINO080** [comment] 2017-10-22 15:22
they never put a repeat command in so it's basically classed as a "modified bot". You can't be helped with modified bots so don't post this here. thanks

**Comment by computergeek125** [comment] 2017-10-23 04:03
duplicate of #486

**Closed as completed** 2017-11-29 03:40 UTC
Labels: s/pebkac
