### ISSUE TITLE
"Failed to parse JSON" after "!play music_name" command

### ISSUE THREAD

**Issue by blaehxd** [Just-Some-Bots/MusicBot#2155] opened 2020-10-25 12:43 UTC
Please tick all applicable boxes.

- [x] I am using Python 3.5.3 or higher (run `python --version` on the command line)
- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [ ] The latest `master` version (release-260419)
- [x] The latest `review` version

What type of issue are you creating?

- [x] Bug
- [ ] Feature request
- [ ] Question

----

### Description of issue
When i try to play a song from youtube by entering its name (!play Flo Rida - Right Round) i get a "Failed to parse JSON" error and the music does not play.
Entering youtube url does work.

### Steps to reproduce

1. Install the bot using [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) with review version.
2. Update the bot and dependecies.
3. Configure the bot by adding token.
4. Start the bot.
5. Try playing a music by entering !play music_name

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**

[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/5434719/musicbot.log)

**Comment by AleanaA** [comment] 2020-10-25 12:45
Duplicate of #2152

**Closed as completed by AleanaA** 2020-10-25 12:45 UTC
