### ISSUE TITLE
Bot crashes after startup

### ISSUE THREAD

**Issue by blaehxd** [Just-Some-Bots/MusicBot#2154] opened 2020-10-25 12:24 UTC
Please tick all applicable boxes.

- [x] I am using Python 3.5.3 or higher (run `python --version` on the command line)
- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [x] The latest `master` version (release-260419)
- [ ] The latest `review` version

What type of issue are you creating?

- [x] Bug
- [ ] Feature request
- [ ] Question

----

### Description of issue
The Bot immediately crashes after starting.

I tried:
- Running the bot on Windows 10, Lubuntu
- Reinstalling Git and Python 3.7.

### Steps to reproduce

1. Follow the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) and download the master version.
2. Configure the bot (i only added the bot token and set BindToChannels)
3. Update the bot and dependecies.
4. Run the bot.
5. Crash.

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**

[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/5434673/musicbot.log)

**Comment by AleanaA** [comment] 2020-10-25 12:27
Duplicate of #2100 resolved in review.

**Closed as completed by AleanaA** 2020-10-25 12:27 UTC
