### ISSUE TITLE
Queue not playing unless !skip is used

### ISSUE THREAD

**Issue by wallopthecat** [Just-Some-Bots/MusicBot#1602] opened 2018-05-02 09:21 UTC
Please tick all applicable boxes.

- [x] I am using Python 3.5 or higher (run `python --version` on the command line)
- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [ ] The latest `master` version (1.9.7)
- [x] The latest `review` version

What type of issue are you creating?

- [x] Bug
- [ ] Feature request
- [ ] Question

----

### Description of issue
Queued songs play one at a time, stopping after each one until !skip is used

### Steps to reproduce

1. Queue more than one song from any source
2. After song 1 ends, song 2 does not start unless `!skip` is used

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**

```
[37mPausing in Mercury/General (empty channel)[0m
[37m148807225132056576/slant⚡#0001: !play bones hdmi[0m
[37mDownload cached: https://www.youtube.com/watch?v=5souw4K5UQc[0m
[37m148807225132056576/slant⚡#0001: !skip[0m
[37m148807225132056576/slant⚡#0001: !skip[0m
The next song will be played shortly.  Please wait.
[31m[ERROR:bot] Exception in on_message
Traceback (most recent call last):
  File "/usr/src/musicbot/musicbot/bot.py", line 2678, in on_message
    response = await handler(**handler_kwargs)
  File "/usr/src/musicbot/musicbot/bot.py", line 2037, in cmd_skip
    current_entry.title,
AttributeError: 'NoneType' object has no attribute 'title'[0m
[37m88068542318014464/wallop#5740: !play lil uzi vert[0m
[37mDownload started: https://www.youtube.com/watch?v=WrsFXgQk5UI[0m
[37m88068542318014464/wallop#5740: !play lil xan[0m
[37mDownload complete: https://www.youtube.com/watch?v=WrsFXgQk5UI[0m
[37m88068542318014464/wallop#5740: !play lil peep benz[0m
[37m88068542318014464/wallop#5740: !skip[0m
[37mDownload started: https://www.youtube.com/watch?v=EbfK7dei7ec[0m
[37mDownload complete: https://www.youtube.com/watch?v=EbfK7dei7ec[0m
[37m148807225132056576/slant⚡#0001: !skip[0m
[37mDownload started: https://www.youtube.com/watch?v=3rkJ3L5Ce80[0m
[37mDownload complete: https://www.youtube.com/watch?v=3rkJ3L5Ce80[0m
[37m88068542318014464/wallop#5740: !queue[0m
[37m148807225132056576/slant⚡#0001: !skip[0m
[37m88068542318014464/wallop#5740: !play afroman palmdale[0m
[37mDownload cached: https://www.youtube.com/watch?v=zWylUZub5KM[0m
[37m88068542318014464/wallop#5740: !skip[0m
[37mDownload started: https://youtube.com/watch?v=iqtmUC6L9fc[0m
[37mDownload complete: https://youtube.com/watch?v=iqtmUC6L9fc[0m
[37m88068542318014464/wallop#5740: !play faygo dreams[0m
[37m88068542318014464/wallop#5740: !skip[0m
[37mDownload started: https://www.youtube.com/watch?v=r1_w4iKar_8[0m
[37mDownload complete: https://www.youtube.com/watch?v=r1_w4iKar_8[0m
[37m88068542318014464/wallop#5740: !queue[0m
[37m88068542318014464/wallop#5740: !skip[0m
[37m88068542318014464/wallop#5740: !play spotify:user:spotify:playlist:37i9dQZF1DWVk7x1ClrO0Y[0m
[37mDownload started: https://www.youtube.com/watch?v=jO6kzetYo0A[0m
[37mDownload complete: https://www.youtube.com/watch?v=jO6kzetYo0A[0m
[37m148807225132056576/slant⚡#0001: !skip[0m
[37mDownload started: https://www.youtube.com/watch?v=xdHnces6UGo[0m
[37mDownload complete: https://www.youtube.com/watch?v=xdHnces6UGo[0m
[37m88068542318014464/wallop#5740: !skip[0m
[37mDownload cached: https://www.youtube.com/watch?v=r1_w4iKar_8[0m
[37m88068542318014464/wallop#5740: !skip[0m
[37mDownload started: https://www.youtube.com/watch?v=h3EJICKwITw[0m
[37mDownload complete: https://www.youtube.com/watch?v=h3EJICKwITw[0m
[37m88068542318014464/wallop#5740: !skip[0m
[37mDownload started: https://www.youtube.com/watch?v=hTLrY2tJkcc[0m
[37mDownload complete: https://www.youtube.com/watch?v=hTLrY2tJkcc[0m
[37m88068542318014464/wallop#5740: !skip[0m
[37mDownload started: https://www.youtube.com/watch?v=ToY6sjSV8h8[0m
[37mDownload complete: https://www.youtube.com/watch?v=ToY6sjSV8h8[0m
[37m
Reconnected to discord.
[0m
[37m
Reconnected to discord.
[0m
[37m88068542318014464/wallop#5740: !skip[0m
[37mDownload started: https://www.youtube.com/watch?v=WlosjSe5B8c[0m
[37mDownload complete: https://www.youtube.com/watch?v=WlosjSe5B8c[0m
[37m88068542318014464/wallop#5740: !play[0m
[37m88068542318014464/wallop#5740: !skip[0m
[37mDownload started: https://www.youtube.com/watch?v=mZu6wbj-juQ[0m
[37mDownload complete: https://www.youtube.com/watch?v=mZu6wbj-juQ[0m
[37m88068542318014464/wallop#5740: !skip[0m
[37mDownload started: https://www.youtube.com/watch?v=rNCuKvEEcb0[0m
[37mDownload complete: https://www.youtube.com/watch?v=rNCuKvEEcb0[0m
```

**Comment by MattBSG** [comment] 2018-05-02 10:34
Duplicate of #1581

**Closed as completed by MattBSG** 2018-05-02 10:34 UTC
Labels: s/dupe
