### ISSUE TITLE
bot randomly stopped working

### ISSUE THREAD

**Issue by shotty46290** [Just-Some-Bots/MusicBot#1965] opened 2019-10-16 15:45 UTC
Please tick all applicable boxes.

- [x] I am using Python 3.5.3 or higher (run `python --version` on the command line)
- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [x] The latest `master` version (release-260419)
- [ ] The latest `review` version

What type of issue are you creating?

- [x] Bug
- [ ] Feature request
- [ ] Question

----

### Description of issue
The bot worked perfectly fine I pretty much run it 24/7 and just join discord when I want to listen to music, today I joined to listen to some music and it wasn't playing tried the !restart command and still didn't play anything. I shut the bot down and updated the dependencies there were a couple of updates, but still no music plays, and in the command prompt the bot is stuck "attempting to join channel." even though the bot comes into the channel but plays no music.

### Steps to reproduce

1. Not a single clue nothing changed just stopped working

----

### Log file
[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/3735175/musicbot.log)

**Comment by TheerapakG** [comment] 2019-10-16 15:51
Duplicate of #1962

**Closed as completed by TheerapakG** 2019-10-16 15:51 UTC
Labels: s/dupe

**Comment by shotty46290** [comment] 2019-10-16 16:23
ok, but his was also closed with no resolve, so its just close anything reference this problem and telling anyone with this problem to go fuck themselves? You sent me a link to a request that was already closed with no resolve so I really don't understand why you are closing this one
