### ISSUE TITLE
Connection Error

### ISSUE THREAD

**Issue by ilovesmok** [Just-Some-Bots/MusicBot#1868] opened 2019-04-09 08:46 UTC
Please tick all applicable boxes.

- [X] I am using Python 3.5 or higher (run `python --version` on the command line)
- [X] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [X] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [X] The latest `master` version (1.9.8)
- [ ] The latest `review` version

What type of issue are you creating?

- [X] Bug
- [ ] Feature request
- [ ] Question

----

When launching the bot, an error comes up saying the bot failed to join whatever channel it's supposed to connect to. It still "connects" to the channel, but when trying to add any song it comes up with a message saying it needs to be summoned, and when using the summon command, it does nothing but provide the same error message in the command prompt.

### Steps to reproduce

1. Run update.bat
2. Run run.bat
3. ?????
4. !summon command

----

### Log file
[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/3057955/musicbot.log)

**Comment by AleanaA** [comment] 2019-04-09 08:47
Duplicate of #1866

**Closed as completed** 2019-04-22 15:38 UTC
Labels: s/dupe
