### ISSUE TITLE
Error 403: Forbidden for all non cached songs

### ISSUE THREAD

**Issue by IlluminatiSanta** [Just-Some-Bots/MusicBot#2071] opened 2020-04-30 23:35 UTC
Please tick all applicable boxes.

- [ /] I am using Python 3.5.3 or higher (run `python --version` on the command line)
- [/ ] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [ ] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [ /] The latest `master` version (release-260419)
- [ ] The latest `review` version

What type of issue are you creating?

- [/ ] Bug
- [ ] Feature request
- [/ ] Question

----

### Description of issue
The bot has been working fine for the past two days since install and running; however, now all song requests that aren't in my audio cache will return error 403: Forbidden
Deleted old Files and reinstalled with the same issue continuing. Did not check the box for applying all updates since when I do update the bot, the console returns "could not build wheels for" each item due to missing package 'wheel'. Thank you for any help you can provide :)

### Steps to reproduce

1. use !play command for any youtube link or song

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**

[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/4561859/musicbot.log)

**Comment by AleanaA** [comment] 2020-05-01 00:02
Duplicate of #2060

**Closed as completed by AleanaA** 2020-05-01 00:02 UTC
