### ISSUE TITLE
AttributeError: 'ClientUser' object has no attribute 'avatar_url'

### ISSUE THREAD

**Issue by Razorbackfr** [Just-Some-Bots/MusicBot#2312] opened 2022-08-28 14:05 UTC
### What went wrong?

When i try, to add a music with !play or i want see the playlist with !queue, i have the following error : 

Traceback (most recent call last):
  File "/home/valentin/MusicBot/musicbot/bot.py", line 4057, in on_message
    response = await handler(**handler_kwargs)
  File "/home/valentin/MusicBot/musicbot/bot.py", line 1649, in cmd_play
    return await self._cmd_play(
  File "/home/valentin/MusicBot/musicbot/bot.py", line 1707, in _cmd_play
    content = self._gen_embed()
  File "/home/valentin/MusicBot/musicbot/bot.py", line 1361, in _gen_embed
    icon_url=self.user.avatar_url,
AttributeError: 'ClientUser' object has no attribute 'avatar_url'

### How do we reproduce this?

Add the music or list the queue

### Which version of the bot are you using?

I am using the "review" branch

### Which operating system are you using?

Ubuntu 18.04 or higher

### Just checking...

- [X] I have confirmed that my issue has not already been reported.
- [X] I am using Python 3.8 or higher.
- [X] I have updated my Python dependencies.

**Comment by x04ty29er** [comment] 2022-09-02 00:32
This appears to be related the change mentioned in this thread (https://github.com/Rapptz/discord.py/issues/7330) that replaced avatar_url with avatar.url.
Patching this locally appears to resolve this issue.

**Comment by Razorbackfr** [comment] 2022-09-02 12:31
I tried to patch myself but changes are overwritten every time the bot is started.

You can't directly patch the code of the review branch?

**Comment by jogerj** [comment] 2022-10-16 21:32
Seems like replacing 2 lines in bot.py from `avatar_url` to `avatar.url` fixed it for me

`sed -i "s/avatar_url/avatar.url/g" ./musicbot/bot.py`

**Comment by jogerj** [comment] 2022-10-16 21:36
Duplicate of #2294 #2290 , resolved by #2308

**Closed as completed** 2022-10-17 00:13 UTC
Labels: t/bug, needs triage
