### ISSUE TITLE
[Bug] !Skip will jump over multiple songs

### ISSUE THREAD

**Issue by BinaryBandit** [Just-Some-Bots/MusicBot#158] opened 2016-03-24 23:30 UTC
I have just upgraded to Rc7, and when i use the skip command it will jump over five to ten songs within the queue. It does not always do this, i think its mainly when downloading new songs.

**Comment by xClow** [comment] 2016-03-25 06:57
Also having this problem with Rc7. No other issues so far though!

**Comment by Echoskope** [comment] 2016-03-27 04:36
Has to do with when the bot checks the links for validity when added to the queue and then keeps the connection to youtube open too long causing it to time out and the bot to skip over everything else in the queue (that is youtube).

**Comment by imayhaveborkedit** [comment] 2016-03-27 05:29
I am unable to reproduce this.  I know multiple people have this happen, but I have yet to see it happen.  I can't fix a bug that doesn't exist for me, so I can't really fix this right now.  Maybe i'll find/fix it by accident, but I have nothing to go on right now.  If someone can reliably reproduce this, please let me know exactly how.

**Comment by Echoskope** [comment] 2016-03-27 05:33
Setup the queue with several youtube videos (like 7ish) in a row (i.e. all requested within a few mins). After the 3rd or 4th one you'll notice the bot will skip through the rest of the list because the server connections have timed out.

**Comment by xClow** [comment] 2016-03-27 05:38
If I add a big playlist and type !skip once every couple seconds I can make it happen after a few skips (5-10 !skips and it will usually start randomly skipping through the songs)

After doing it enough times it just skipped through an entire playlist in like 15 seconds flat http://i.imgur.com/ApDep4u.png

**Comment by imayhaveborkedit** [comment] 2016-03-27 06:40
@Echoskope I'm not sure where you got this "connection timed out" idea from, but that's not how the bot works.  Resolving urls and playlists is all done by youtube_dl.  If something connection related is breaking, it's part of that library.  

In the case of youtube playlists, I did a trick to queue the songs sequentially instead of having to wait for youtube_dl to resolve the entire playlist first, which can take a long time with a large playlist.  Instead of having youtube_dl process the entire playlist, I get the unprocessed version of the playlist, generate the urls myself, and queue each of those urls individually.  Skipping during this part shouldn't break anything, but i'll do some more testing.

**Comment by Echoskope** [comment] 2016-03-27 15:00
@imayhaveborkedit I spent some time last night trying to recreate the problem just to make sure I'm not crazy but couldn't get it to do it again :( Maybe the problem we ran into was a red herring.

**Comment by Zephyrrus** [comment] 2016-04-10 10:16
@Echoskope Nope, this is a problem affecting my bot and one of my friends bot too, what I noticed that a song starts playing, ffmpeg freezes/crashes and then the next 5-6 songs get skipped. I posted detailed logs of what's going on and what events are getting fired when this happens but I got ignored cause it only affects some users.

**Comment by imayhaveborkedit** [comment] 2016-05-02 21:41
I'm fairly sure this is gone now since people have stopped mentioning it.

**Closed as completed by imayhaveborkedit** 2016-05-02 21:41 UTC
Labels: t/bug, s/help wanted
