### ISSUE TITLE
Keep Duration/Total file size limit for the downloaded audio files

### ISSUE THREAD

**Issue by felix920506** [Just-Some-Bots/MusicBot#1817] opened 2019-01-12 10:46 UTC
Please tick all applicable boxes.

- [x] I am using Python 3.5 or higher (run `python --version` on the command line)
- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [x] The latest `master` version (1.9.8)
- [ ] The latest `review` version

What type of issue are you creating?

- [ ] Bug
- [x] Feature request
- [ ] Question

----

### Description of issue
Saving the downloaded audio files takes up a lot of space but not saving it causes delays when playing songs. Can you add the option to delete the audio files after it reaches a certain duration without being played or when the folder reaches a set limit in size

**Comment by AleanaA** [comment] 2019-01-12 10:48
Duplicate of #1584

**Closed as completed** 2019-01-16 01:08 UTC
Labels: s/dupe, t/request, a/playback
