### ISSUE TITLE
My Musicbot has a problem

### ISSUE THREAD

**Issue by zxphet2540** [Just-Some-Bots/MusicBot#2072] opened 2020-05-02 05:53 UTC
Please tick all applicable boxes.

- [ /] I am using Python 3.5.3 or higher (run `python --version` on the command line)
- [/ ] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [ /] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [/ ] The latest `master` version (release-260819)
- [ ] The latest `review` version

What type of issue are you creating?

- [/ ] Bug
- [ ] Feature request
- [/ ] Question

----
### Steps to reproduce

// The language I use to type may have some strange words because I am not proficient in English.

1.I have tried to remove python 3.7, new Git Bash, MusicBot and try to install several times, still encountering the above problem.
2.I have restored windows 10 and reset windows 10

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**
[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/4567161/musicbot.log)

**Comment by zxphet2540** [comment] 2020-05-02 05:59
<a href="https://www.img.in.th/image/UB8qlE"><img src="https://s3-ap-southeast-1.amazonaws.com/img-in-th/76adaa01db9df6b38cf68f338e97bb49.md.png" alt="76adaa01db9df6b38cf68f338e97bb49.png" border="0" /></a>
<img src="https://s3-ap-southeast-1.amazonaws.com/img-in-th/b449b2679ca9e8b939ef44ba14c65dba.png" alt="b449b2679ca9e8b939ef44ba14c65dba.png" border="0" />

**Comment by AleanaA** [comment] 2020-05-02 05:59
Duplicate of #2060

**Closed as completed by AleanaA** 2020-05-02 05:59 UTC
Labels: s/invalid
