### ISSUE TITLE
UseAutoPlaylist setting to no does not clear queue

### ISSUE THREAD

**Issue by Saper140** [Just-Some-Bots/MusicBot#2037] opened 2020-03-25 16:36 UTC
Please tick all applicable boxes.

- [x] I am using Python 3.5.3 or higher (run `python --version` on the command line)
- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [x] The latest `master` version (release-260419)
- [ ] The latest `review` version

What type of issue are you creating?

- [ ] Bug
- [ ] Feature request
- [x] Question

----

### Description of issue
When setting the `UseAutoPlaylist` to `no` does not clear the queue so after restarting the bot,  (since it already had auto queued from the playlist) it continues from the queue. This is a little confusing because there is no documentation mentioning you should clear the queue when setting that setting or the bot doesn't auto clear the queue when that setting is changed.

I think it would be nice to have some mention of that in the documentation and in the options.ini file. 

### Steps to reproduce

1. start the bot from fresh install
2. stop the bot
3. change the `UseAutoPlaylist` to `no` in options.ini
4. start the bot
5. summon bot
6. get confused because your smawlbrain

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**

**Comment by Roadhog360** [comment] 2020-03-25 16:43
There is an option which remembers the song in the playlist called 'persistentQueue', which remembers all songs in the queue between restarts, including what was currently playing. This is not a bug because it's still remembering it like any other song. Turn off persistentQueue or skip it.

**Closing: Works as Intended**

**Closed as completed** 2020-03-25 16:43 UTC
Labels: s/wontfix, a/options
