### ISSUE TITLE
Joins channel will not respond to commands.

### ISSUE THREAD

**Issue by jvelasq** [Just-Some-Bots/MusicBot#1964] opened 2019-10-16 04:18 UTC
Please tick all applicable boxes.

- [ x] I am using Python 3.5.3 or higher (run `python --version` on the command line)
- [x ] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x ] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [ x] The latest `master` version (release-260419)
- [ ] The latest `review` version

What type of issue are you creating?

- [x ] Bug
- [ ] Feature request
- [x ] Question

----

### Description of issue

I Have been using this music bot for at least 8 or 9 months now and last night it worked just fine. today I tried to start the bot and it would not play music so i updated the dependencies since that's what normally fixes the issue. this time it did not fix it and the issue still happened. the only this that has changes is i downloaded Glasswire network monitor.
[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/3732410/musicbot.log)

### Steps to reproduce

1. Download glasswire.
2. update dependencies. 

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**

**Comment by AleanaA** [comment] 2019-10-16 04:20
Duplicate of #1962

**Closed as completed by AleanaA** 2019-10-16 04:20 UTC
Labels: s/dupe
