### ISSUE TITLE
AutoPlaylistRandom doesn't work

### ISSUE THREAD

**Issue by Aur3m** [Just-Some-Bots/MusicBot#1820] opened 2019-01-15 22:11 UTC
Please tick all applicable boxes.

- [ .] I am using Python 3.5 or higher (run `python --version` on the command line)
- [ .] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [. ] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [ .] The latest `master` version (1.9.8)
- [ ] The latest `review` version

What type of issue are you creating?

- [. ] Bug
- [ ] Feature request
- [ ] Question

----

### Description of issue
AutoPlaylistRandom function doesn't work I have activated AutoPlaylist and it autojoin the channel but pley the music sequencially

### Steps to reproduce

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**
[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/2761679/musicbot.log)

**Comment by AutumnClove** [comment] 2019-04-23 21:18
For it to be random please make sure the AutoPlaylistRandom is set to yes, and you've cleared out your queue. Closing due to unable to reproduce.

**Closed as completed by AutumnClove** 2019-04-23 21:18 UTC
