### ISSUE TITLE
Won't answer to play requests

### ISSUE THREAD

**Issue by zNoah-1** [Just-Some-Bots/MusicBot#1966] opened 2019-10-17 08:50 UTC
Please tick all applicable boxes.

- [x] I am using Python 3.5.3 or higher (run `python --version` on the command line)
- [x] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [x] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [x] The latest `master` version (release-260419)
- [ ] The latest `review` version

What type of issue are you creating?

- [x] Bug
- [ ] Feature request
- [ ] Question

----

### Description of issue

The bot doesn't play any music, there's no voice activity coming from the bot. It doesn't answer to play, queue commands.

I tried giving it more permissions and made sure it have permissions to talk.

This is my config file: 
[options.txt](https://github.com/Just-Some-Bots/MusicBot/files/3738265/options.txt)

### Steps to reproduce

1. Run the bot
2. Request song

Example: 
![image](https://user-images.githubusercontent.com/15351267/66993156-ba1e1000-f090-11e9-8b83-78f124219f9b.png)

----

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**
[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/3738229/musicbot.log)

**Comment by AleanaA** [comment] 2019-10-17 08:52
Duplicate of #1962

**Closed as completed by AleanaA** 2019-10-17 08:52 UTC
Labels: s/dupe
