### ISSUE TITLE
Not working with Python 3.8.0

### ISSUE THREAD

**Issue by A1H1** [Just-Some-Bots/MusicBot#2083] opened 2020-06-04 16:28 UTC
Please tick all applicable boxes.

- [*] I am using Python 3.5.3 or higher (run `python --version` on the command line)
- [*] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [*] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- [*] The latest `master` version (release-260419)
- [ ] The latest `review` version

What type of issue are you creating?

- [*] Bug
- [ ] Feature request
- [ ] Question

----

### Description of issue
Unable to start the bot with python 3.8.2

### Steps to reproduce

1. Start the bot with python 3.8

----

[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/4731151/musicbot.log)

### Log file
Please attach your MusicBot log file (located at `logs/musicbot.log`) to this issue. You can do so by dragging and dropping the file here. **If you do not include your log file, you WILL be asked to provide one.**

**Comment by AleanaA** [comment] 2020-06-04 16:47
Duplicate of #2015

**Closed as completed by AleanaA** 2020-06-04 16:47 UTC
