### ISSUE TITLE
Issue with a youtube playlist

### ISSUE THREAD

**Issue by m0nsteer** [Just-Some-Bots/MusicBot#1913] opened 2019-06-03 00:55 UTC
Please tick all applicable boxes.

- [X] I am using Python 3.5.3 or higher (run `python --version` on the command line)
- [X] I have followed the [official guides](https://github.com/Just-Some-Bots/MusicBot/wiki) to install the bot for my system
- [X] I have updated my dependencies to the latest version using the appropriate `update` script

Which version are you using?

- MusicBot release-120519

What type of issue are you creating?

- [ ] Bug
- [ ] Feature request
- [X] Question

### Description of issue

I created a Youtube Playlist with lots of songs, the playlist was working well, yesterday I added like 50 songs more and when I tried to put it on the bot, some copyright issue on any song comes up, but I can't know which song, how can I know the exact song?

Sorry if my english was bad and thanks for your time.

[musicbot.log](https://github.com/Just-Some-Bots/MusicBot/files/3245447/musicbot.log)

**Comment by AutumnClove** [comment] 2019-06-03 02:38
There's an option to auto take out bad entries just turn that on

**Comment by AutumnClove** [comment] 2019-06-03 02:40
https://github.com/Just-Some-Bots/MusicBot/blob/master/config/example_options.ini#L170-#L173

**Comment by TheerapakG** [comment] 2019-06-03 02:42
@AutumnClove That's for autoplaylist

**Comment by TheerapakG** [comment] 2019-06-03 02:43
But it's kinda duplicate of #1891

**Comment by AutumnClove** [comment] 2019-06-03 02:55
My bad I thought they meant this was occuring to the AP, however shouldn't there be a error message in the log saying `error processing {url}` you could copy that url and enter it in a browser. Boom profit?

**Comment by AutumnClove** [comment] 2019-06-03 03:03
Oh wait I think that's just for autoplaylist, I don't think we have something like that implemented for regular playlist, but I mean it will still play the rest of the playlist so I'm not really sure that would be necessary other than to maybe save some log space because that's a lot less space than this video etc etc

**Comment by m0nsteer** [comment] 2019-06-03 11:00
When I put the playlist, that error comes up and the bot doesn't add any song.

**Comment by BabyBoySnow** [comment] 2023-08-04 17:43
#1860

**Closed as completed by BabyBoySnow** 2023-08-04 17:43 UTC
Labels: t/bug, t/q&a, t/request
